<?php

return [
    'list' => [
        ['title' => 'Everlasting Life', 'image' => '/images/everlasting-life.jpg'],
        ['title' => 'Subverse', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1034140/library_600x900.jpg'],
        ['title' => 'House Party', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/611790/library_600x900.jpg'],
        ['title' => 'Being a DIK', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1126320/library_600x900.jpg'],
        ['title' => 'Lust Theory', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1279140/library_600x900.jpg'],
        ['title' => 'Lessons in Love', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1629850/library_600x900.jpg'],
        ['title' => 'Fresh Women', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1792630/library_600x900.jpg'],
        ['title' => 'Orc Massage', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1508270/library_600x900.jpg'],
        ['title' => 'Custom Order Maid 3D2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1097580/library_600x900.jpg'],
        ['title' => 'NekoPara Vol. 1', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/333600/library_600x900.jpg'],
        ['title' => 'Summer Memories', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1227890/library_600x900.jpg'],
        ['title' => 'Winter Memories', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2445430/library_600x900.jpg'],
        ['title' => 'Evenicle', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/955560/library_600x900.jpg'],
        ['title' => 'Acting Lessons', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1039860/library_600x900.jpg'],
        ['title' => "Love's Sweet Garnish", 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/804900/library_600x900.jpg'],
        ['title' => 'HuniePop 2: Double Date', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/930210/library_600x900.jpg'],
        ['title' => 'HuniePop', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/331800/library_600x900.jpg'],
        ['title' => 'Mirror', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/995070/library_600x900.jpg'],
        ['title' => 'Succubus', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/985830/library_600x900.jpg'],
        ['title' => 'Agony UNRATED', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/874240/library_600x900.jpg'],
        ['title' => 'Grand Theft Auto V', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_600x900.jpg'],
        ['title' => 'Cyberpunk 2077', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_600x900.jpg'],
        ['title' => 'The Last of Us Part I', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1888930/library_600x900.jpg'],
        ['title' => 'The Witcher 3: Wild Hunt', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/library_600x900.jpg'],
        ['title' => 'Resident Evil Village', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1196590/library_600x900.jpg'],
        ['title' => 'Doom Eternal', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/782330/library_600x900.jpg'],
        ['title' => 'Elden Ring', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_600x900.jpg'],
        ['title' => "Baldur's Gate 3", 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/library_600x900.jpg'],
        ['title' => 'Outlast 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/414700/library_600x900.jpg'],
        ['title' => 'Dead Space', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1693980/library_600x900.jpg'],
        ['title' => 'Detroit: Become Human', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1083860/library_600x900.jpg'],
        ['title' => 'Red Dead Redemption 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/library_600x900.jpg'],
        ['title' => 'Mortal Kombat 1', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1787070/library_600x900.jpg'],
        ['title' => 'God of War Ragnarök', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2322010/library_600x900.jpg'],
        ['title' => 'Hitman World of Assassination', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1659040/library_600x900.jpg'],
        ['title' => 'Far Cry 6', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2369390/library_600x900.jpg'],
        ['title' => 'Diablo IV', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2344520/library_600x900.jpg'],
        ['title' => 'Final Fantasy XVI', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2515020/library_600x900.jpg'],
        ['title' => 'Resident Evil 4', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/library_600x900.jpg'],
        ['title' => 'Street Fighter 6', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1364780/library_600x900.jpg'],
        ['title' => 'Valorant', 'image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop'],
        ['title' => 'Starfield', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1716770/library_600x900.jpg'],
        ['title' => 'Hogwarts Legacy', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/990080/library_600x900.jpg'],
        ['title' => 'Call of Duty: Modern Warfare', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1938090/library_600x900.jpg'],
        ['title' => 'Counter-Strike 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/730/library_600x900.jpg'],
        ['title' => 'League of Legends', 'image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop'],
        ['title' => 'Dota 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/library_600x900.jpg'],
        ['title' => 'Overwatch 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2357570/library_600x900.jpg'],
        ['title' => 'Apex Legends', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1172470/library_600x900.jpg'],
        ['title' => 'Fortnite', 'image' => 'https://images.unsplash.com/photo-1589241062272-c0a000072dfa?q=80&w=600&auto=format&fit=crop'],
        ['title' => 'Minecraft', 'image' => 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?q=80&w=600&auto=format&fit=crop'],
        ['title' => 'Terraria', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/105600/library_600x900.jpg'],
        ['title' => 'Stardew Valley', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/library_600x900.jpg'],
        ['title' => 'The Sims 4', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1222670/library_600x900.jpg'],
        ['title' => 'Cities: Skylines', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/255710/library_600x900.jpg'],
        ['title' => 'Civilization VI', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/289070/library_600x900.jpg'],
        ['title' => 'XCOM 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/268500/library_600x900.jpg'],
        ['title' => 'Total War: Warhammer III', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1142710/library_600x900.jpg'],
        ['title' => 'Hades', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/library_600x900.jpg'],
        ['title' => 'Dead Cells', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/588650/library_600x900.jpg'],
        ['title' => 'Hollow Knight', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/library_600x900.jpg'],
        ['title' => 'Celeste', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/504230/library_600x900.jpg'],
        ['title' => 'Ori and the Will of the Wisps', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1057090/library_600x900.jpg'],
        ['title' => 'Dark Souls III', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/374320/library_600x900.jpg'],
        ['title' => 'Sekiro: Shadows Die Twice', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/814380/library_600x900.jpg'],
        ['title' => 'Bloodborne', 'image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?q=80&w=600&auto=format&fit=crop'],
        ['title' => 'Monster Hunter: World', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/582010/library_600x900.jpg'],
        ['title' => 'Destiny 2', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1085660/library_600x900.jpg'],
        ['title' => 'Warframe', 'image' => 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/230410/library_600x900.jpg'],
    ],
];
